//! `camera-media-store` — a filesystem-backed camera card model.
//!
//! Responsibilities relevant to the simulator: root-confined (symlink-safe)
//! traversal, stable object-handle assignment, `ObjectInfo` generation, bounded
//! partial reads via [`ByteSource`] (never loading whole media files), the
//! 32-bit wireless-transfer ceiling, and bounded RAF preview extraction.

use std::collections::BTreeMap;
use std::fs::File;
use std::io::{Read, Seek, SeekFrom};
use std::path::{Path, PathBuf};

use ptp_core::codes::format;
use ptp_core::ObjectInfo;
use thiserror::Error;

/// Vendor/extra object formats not in `ptp-core`'s standard set.
pub mod fmt {
    /// Fuji RAF raw.
    pub const RAF: u16 = 0xb103;
    /// QuickTime MOV.
    pub const MOV: u16 = 0x300d;
    /// HEIF.
    pub const HEIF: u16 = 0x3818;
}

/// The PTP `ObjectInfo` 32-bit size field cannot represent ≥ 4 GiB. Objects at
/// or beyond this are reported at the ceiling and flagged memory-card-only.
pub const SIZE_CEILING: u64 = u32::MAX as u64;

pub type ObjectHandle = u32;

#[derive(Debug, Error)]
pub enum MediaError {
    #[error("io: {0}")]
    Io(#[from] std::io::Error),
    #[error("unknown object handle {0}")]
    UnknownHandle(ObjectHandle),
    #[error("path escapes media root: {0}")]
    RootEscape(PathBuf),
    #[error("no embedded preview found")]
    NoPreview,
}

/// A bounded source of object bytes. The simulator streams these in chunks; a
/// `FileRange` is read with a single seek, so a multi-GB object never lands in
/// memory.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ByteSource {
    Memory(Vec<u8>),
    FileRange {
        path: PathBuf,
        offset: u64,
        len: u64,
    },
    /// Deterministic generated bytes (seeded) — for synthetic fixtures.
    Generated {
        len: u64,
        seed: u64,
    },
}

impl ByteSource {
    pub fn len(&self) -> u64 {
        match self {
            ByteSource::Memory(b) => b.len() as u64,
            ByteSource::FileRange { len, .. } => *len,
            ByteSource::Generated { len, .. } => *len,
        }
    }

    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }

    /// Realize the bytes. For `FileRange`, reads exactly the window via seek —
    /// allocating only `len` bytes regardless of the file's total size.
    pub fn read(&self) -> Result<Vec<u8>, MediaError> {
        match self {
            ByteSource::Memory(b) => Ok(b.clone()),
            ByteSource::FileRange { path, offset, len } => {
                let mut f = File::open(path)?;
                f.seek(SeekFrom::Start(*offset))?;
                let mut buf = vec![0u8; *len as usize];
                let n = read_full(&mut f, &mut buf)?;
                buf.truncate(n);
                Ok(buf)
            }
            ByteSource::Generated { len, seed } => Ok((0..*len)
                .map(|i| (i.wrapping_mul(2654435761).wrapping_add(*seed)) as u8)
                .collect()),
        }
    }
}

fn read_full(f: &mut File, buf: &mut [u8]) -> std::io::Result<usize> {
    let mut filled = 0;
    while filled < buf.len() {
        match f.read(&mut buf[filled..])? {
            0 => break,
            n => filled += n,
        }
    }
    Ok(filled)
}

#[derive(Debug, Clone)]
struct Entry {
    handle: ObjectHandle,
    path: PathBuf,
    parent: ObjectHandle,
    is_dir: bool,
    size: u64,
    format: u16,
}

#[derive(Debug, Default, Clone, Copy)]
pub struct ObjectQuery {
    /// `Some(0)` means top-level (root) objects; `Some(h)` children of `h`.
    pub parent: Option<ObjectHandle>,
    pub format: Option<u16>,
}

#[derive(Debug, Default)]
pub struct ScanSummary {
    pub objects: usize,
    pub bytes: u64,
}

pub struct MediaStore {
    root: PathBuf,
    by_handle: BTreeMap<ObjectHandle, Entry>,
}

impl MediaStore {
    /// Open a store rooted at `root`. The root is canonicalized; all later
    /// traversal is confined beneath it.
    pub fn open(root: impl AsRef<Path>) -> Result<Self, MediaError> {
        let root = root.as_ref().canonicalize()?;
        Ok(MediaStore {
            root,
            by_handle: BTreeMap::new(),
        })
    }

    pub fn root(&self) -> &Path {
        &self.root
    }

    /// Walk the card and assign stable handles. Handles are assigned in sorted
    /// path order so the same card yields the same handles across runs.
    /// Symlinks whose target escapes the root are skipped.
    pub fn scan(&mut self) -> Result<ScanSummary, MediaError> {
        let mut paths: Vec<(PathBuf, bool, u64)> = Vec::new();
        self.collect(&self.root.clone(), &mut paths)?;
        // Deterministic order -> stable handles.
        paths.sort_by(|a, b| a.0.cmp(&b.0));

        self.by_handle.clear();
        // First pass: assign handles to every path.
        let mut handle_of: BTreeMap<PathBuf, ObjectHandle> = BTreeMap::new();
        for (i, (path, _, _)) in paths.iter().enumerate() {
            handle_of.insert(path.clone(), (i as u32) + 1);
        }
        let mut summary = ScanSummary::default();
        for (path, is_dir, size) in paths {
            let handle = handle_of[&path];
            let parent = path
                .parent()
                .and_then(|p| handle_of.get(p))
                .copied()
                .unwrap_or(0); // 0 = root association
            let format = if is_dir {
                format::ASSOCIATION
            } else {
                format_of(&path)
            };
            if !is_dir {
                summary.bytes += size;
            }
            summary.objects += 1;
            self.by_handle.insert(
                handle,
                Entry {
                    handle,
                    path,
                    parent,
                    is_dir,
                    size,
                    format,
                },
            );
        }
        Ok(summary)
    }

    fn collect(&self, dir: &Path, out: &mut Vec<(PathBuf, bool, u64)>) -> Result<(), MediaError> {
        for entry in std::fs::read_dir(dir)? {
            let entry = entry?;
            let path = entry.path();
            // Resolve symlinks safely: a link whose real target leaves the root
            // is dropped entirely.
            let meta = std::fs::symlink_metadata(&path)?;
            let real = if meta.file_type().is_symlink() {
                match path.canonicalize() {
                    Ok(t) if t.starts_with(&self.root) => t,
                    _ => continue, // escapes root (or dangling) -> skip
                }
            } else {
                path.clone()
            };
            let real_meta = std::fs::metadata(&real)?;
            if real_meta.is_dir() {
                out.push((path.clone(), true, 0));
                self.collect(&path, out)?;
            } else {
                out.push((path.clone(), false, real_meta.len()));
            }
        }
        Ok(())
    }

    fn entry(&self, handle: ObjectHandle) -> Result<&Entry, MediaError> {
        self.by_handle
            .get(&handle)
            .ok_or(MediaError::UnknownHandle(handle))
    }

    /// Confirm a path is inside the root (defense in depth for any external
    /// path).
    pub fn assert_within_root(&self, path: &Path) -> Result<(), MediaError> {
        let canon = path
            .canonicalize()
            .map_err(|_| MediaError::RootEscape(path.to_path_buf()))?;
        if canon.starts_with(&self.root) {
            Ok(())
        } else {
            Err(MediaError::RootEscape(path.to_path_buf()))
        }
    }

    pub fn handles(&self, query: ObjectQuery) -> Vec<ObjectHandle> {
        self.by_handle
            .values()
            .filter(|e| query.parent.map(|p| e.parent == p).unwrap_or(true))
            .filter(|e| query.format.map(|f| e.format == f).unwrap_or(true))
            .map(|e| e.handle)
            .collect()
    }

    /// Generate `ObjectInfo`, applying the 32-bit size ceiling for oversize
    /// objects.
    pub fn object_info(&self, handle: ObjectHandle) -> Result<ObjectInfo, MediaError> {
        let e = self.entry(handle)?;
        let reported_size = e.size.min(SIZE_CEILING) as u32;
        let filename = e
            .path
            .file_name()
            .and_then(|s| s.to_str())
            .unwrap_or("")
            .to_string();
        Ok(ObjectInfo {
            storage_id: 0x0001_0001,
            object_format: e.format,
            object_compressed_size: reported_size,
            parent_object: e.parent,
            association_type: if e.is_dir { 1 } else { 0 },
            filename,
            ..Default::default()
        })
    }

    /// True if the object cannot be wirelessly transferred because its real size
    /// exceeds the 32-bit `ObjectInfo` field (reported at the ceiling).
    pub fn is_memory_card_only(&self, handle: ObjectHandle) -> Result<bool, MediaError> {
        Ok(self.entry(handle)?.size >= SIZE_CEILING)
    }

    pub fn object_size(&self, handle: ObjectHandle) -> Result<u64, MediaError> {
        Ok(self.entry(handle)?.size)
    }

    /// A bounded partial read. Clamps to the object's real length; returns a
    /// `FileRange` so the bytes are streamed, not buffered.
    pub fn read_range(
        &self,
        handle: ObjectHandle,
        offset: u64,
        len: u32,
    ) -> Result<ByteSource, MediaError> {
        let e = self.entry(handle)?;
        let avail = e.size.saturating_sub(offset);
        let len = (len as u64).min(avail);
        Ok(ByteSource::FileRange {
            path: e.path.clone(),
            offset,
            len,
        })
    }

    /// Extract a thumbnail. For RAF, scans a bounded prefix for the embedded
    /// JPEG (SOI..EOI) and returns just that range. For JPEG, returns the file.
    pub fn thumbnail(&self, handle: ObjectHandle) -> Result<ByteSource, MediaError> {
        let e = self.entry(handle)?;
        match e.format {
            fmt::RAF => extract_jpeg_preview(&e.path),
            format::EXIF_JPEG => Ok(ByteSource::FileRange {
                path: e.path.clone(),
                offset: 0,
                len: e.size,
            }),
            // MOV/HEIF/etc: a generated poster placeholder until a real decoder lands.
            _ => Ok(ByteSource::Generated { len: 0, seed: 0 }),
        }
    }
}

fn format_of(path: &Path) -> u16 {
    match path
        .extension()
        .and_then(|s| s.to_str())
        .map(|s| s.to_ascii_lowercase())
        .as_deref()
    {
        Some("jpg") | Some("jpeg") => format::EXIF_JPEG,
        Some("raf") => fmt::RAF,
        Some("mov") => fmt::MOV,
        Some("heif") | Some("heic") => fmt::HEIF,
        _ => format::UNDEFINED,
    }
}

/// How far into a RAF we scan for the embedded JPEG preview before giving up.
const PREVIEW_SCAN_LIMIT: u64 = 4 * 1024 * 1024;

fn extract_jpeg_preview(path: &Path) -> Result<ByteSource, MediaError> {
    let mut f = File::open(path)?;
    let scan = PREVIEW_SCAN_LIMIT.min(f.metadata()?.len());
    let mut buf = vec![0u8; scan as usize];
    let n = read_full(&mut f, &mut buf)?;
    let buf = &buf[..n];
    // JPEG SOI = FF D8, EOI = FF D9.
    let soi = find(buf, &[0xFF, 0xD8]).ok_or(MediaError::NoPreview)?;
    let eoi = find(&buf[soi..], &[0xFF, 0xD9]).ok_or(MediaError::NoPreview)? + soi + 2;
    Ok(ByteSource::FileRange {
        path: path.to_path_buf(),
        offset: soi as u64,
        len: (eoi - soi) as u64,
    })
}

fn find(hay: &[u8], needle: &[u8]) -> Option<usize> {
    hay.windows(needle.len()).position(|w| w == needle)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;

    fn tmpdir() -> PathBuf {
        let nanos = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let d = std::env::temp_dir().join(format!("ptpsim-media-{nanos}"));
        std::fs::create_dir_all(&d).unwrap();
        d
    }

    fn write(path: &Path, bytes: &[u8]) {
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        File::create(path).unwrap().write_all(bytes).unwrap();
    }

    #[test]
    fn scan_assigns_stable_handles_and_filters() {
        let root = tmpdir();
        write(
            &root.join("DCIM/100_FUJI/DSCF0001.JPG"),
            b"\xFF\xD8stuff\xFF\xD9",
        );
        write(&root.join("DCIM/100_FUJI/DSCF0002.RAF"), b"raf");
        let mut s1 = MediaStore::open(&root).unwrap();
        s1.scan().unwrap();
        let mut s2 = MediaStore::open(&root).unwrap();
        s2.scan().unwrap();
        // Stable across independent scans.
        assert_eq!(
            s1.handles(ObjectQuery::default()),
            s2.handles(ObjectQuery::default())
        );
        // Filter by format.
        let jpgs = s1.handles(ObjectQuery {
            parent: None,
            format: Some(format::EXIF_JPEG),
        });
        assert_eq!(jpgs.len(), 1);
        std::fs::remove_dir_all(&root).ok();
    }

    #[test]
    fn symlink_escape_is_rejected_in_root_link_works() {
        let root = tmpdir();
        let outside = tmpdir();
        write(&outside.join("secret.JPG"), b"\xFF\xD8x\xFF\xD9");
        write(&root.join("DCIM/100_FUJI/real.JPG"), b"\xFF\xD8y\xFF\xD9");
        // Escaping symlink.
        #[cfg(unix)]
        std::os::unix::fs::symlink(
            outside.join("secret.JPG"),
            root.join("DCIM/100_FUJI/escape.JPG"),
        )
        .unwrap();
        // In-root symlink.
        #[cfg(unix)]
        std::os::unix::fs::symlink(
            root.join("DCIM/100_FUJI/real.JPG"),
            root.join("DCIM/100_FUJI/inlink.JPG"),
        )
        .unwrap();

        let mut store = MediaStore::open(&root).unwrap();
        store.scan().unwrap();
        let names: Vec<String> = store
            .handles(ObjectQuery::default())
            .into_iter()
            .map(|h| store.object_info(h).unwrap().filename)
            .collect();
        assert!(names.iter().any(|n| n == "real.JPG"));
        assert!(
            names.iter().any(|n| n == "inlink.JPG"),
            "in-root symlink should be visible"
        );
        assert!(
            !names.iter().any(|n| n == "escape.JPG"),
            "escaping symlink must be dropped"
        );

        // Direct guard too.
        assert!(store
            .assert_within_root(&outside.join("secret.JPG"))
            .is_err());
        std::fs::remove_dir_all(&root).ok();
        std::fs::remove_dir_all(&outside).ok();
    }

    #[test]
    fn raf_preview_is_bounded_range() {
        let root = tmpdir();
        // RAF: header, embedded JPEG, trailer.
        let mut raf = Vec::new();
        raf.extend_from_slice(b"FUJIFILMCCD-RAW header padding............");
        let jpeg_off = raf.len();
        raf.extend_from_slice(&[0xFF, 0xD8]); // SOI
        raf.extend_from_slice(b"PREVIEWDATA");
        raf.extend_from_slice(&[0xFF, 0xD9]); // EOI
        let jpeg_end = raf.len();
        raf.extend_from_slice(b"....raw sensor data trailer....");
        write(&root.join("DCIM/100_FUJI/DSCF9.RAF"), &raf);

        let mut store = MediaStore::open(&root).unwrap();
        store.scan().unwrap();
        let h = store.handles(ObjectQuery {
            parent: None,
            format: Some(fmt::RAF),
        })[0];
        let src = store.thumbnail(h).unwrap();
        if let ByteSource::FileRange { offset, len, .. } = &src {
            assert_eq!(*offset, jpeg_off as u64);
            assert_eq!(*len, (jpeg_end - jpeg_off) as u64);
        } else {
            panic!("expected a bounded FileRange");
        }
        let bytes = src.read().unwrap();
        assert_eq!(&bytes[0..2], &[0xFF, 0xD8]);
        assert_eq!(&bytes[bytes.len() - 2..], &[0xFF, 0xD9]);
        std::fs::remove_dir_all(&root).ok();
    }

    #[test]
    fn oversize_mov_is_ceilinged_without_allocation() {
        let root = tmpdir();
        let p = root.join("DCIM/100_FUJI/BIG.MOV");
        std::fs::create_dir_all(p.parent().unwrap()).unwrap();
        // 5 GiB sparse file: set_len does not allocate blocks.
        let f = File::create(&p).unwrap();
        let five_gib = 5u64 * 1024 * 1024 * 1024;
        f.set_len(five_gib).unwrap();
        drop(f);

        let mut store = MediaStore::open(&root).unwrap();
        store.scan().unwrap();
        let h = store.handles(ObjectQuery {
            parent: None,
            format: Some(fmt::MOV),
        })[0];

        // Real size known; ObjectInfo reports the 32-bit ceiling.
        assert_eq!(store.object_size(h).unwrap(), five_gib);
        assert_eq!(
            store.object_info(h).unwrap().object_compressed_size,
            0xffff_ffff
        );
        assert!(store.is_memory_card_only(h).unwrap());

        // A partial read near the end works, allocating only the window.
        let src = store.read_range(h, five_gib - 8, 16).unwrap();
        assert_eq!(src.len(), 8); // clamped to remaining
        assert_eq!(src.read().unwrap().len(), 8);
        std::fs::remove_dir_all(&root).ok();
    }
}
