//! `camera-media-store` — a filesystem-backed camera card model.
//!
//! Responsibilities relevant to the simulator: root-confined (symlink-safe)
//! traversal, stable object-handle assignment, `ObjectInfo` generation, bounded
//! partial reads via [`ByteSource`] (never loading whole media files), the
//! 32-bit wireless-transfer ceiling, and bounded RAF thumbnail extraction.

use std::collections::BTreeMap;
use std::fs::File;
use std::io::{Read, Seek, SeekFrom};
use std::path::{Path, PathBuf};

use ptp_core::codes::format;
use ptp_core::ObjectInfo;
use thiserror::Error;

/// Vendor/extra object formats not in `ptp-core`'s standard set.
pub mod fmt {
    /// Fuji RAF raw.
    pub const RAF: u16 = 0xb103;
    /// QuickTime MOV.
    pub const MOV: u16 = 0x300d;
    /// HEIF.
    pub const HEIF: u16 = 0x3818;
}

/// The PTP `ObjectInfo` 32-bit size field cannot represent ≥ 4 GiB. Objects at
/// or beyond this are reported at the ceiling and flagged memory-card-only.
pub const SIZE_CEILING: u64 = u32::MAX as u64;

pub type ObjectHandle = u32;

#[derive(Debug, Error)]
pub enum MediaError {
    #[error("io: {0}")]
    Io(#[from] std::io::Error),
    #[error("unknown object handle {0}")]
    UnknownHandle(ObjectHandle),
    #[error("path escapes media root: {0}")]
    RootEscape(PathBuf),
    #[error("no embedded thumbnail found")]
    NoPreview,
}

/// A bounded source of object bytes. The simulator streams these in chunks; a
/// `FileRange` is read with a single seek, so a multi-GB object never lands in
/// memory.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ByteSource {
    Memory(Vec<u8>),
    FileRange {
        path: PathBuf,
        offset: u64,
        len: u64,
    },
    /// Deterministic generated bytes (seeded) — for synthetic fixtures.
    Generated {
        len: u64,
        seed: u64,
    },
}

impl ByteSource {
    pub fn len(&self) -> u64 {
        match self {
            ByteSource::Memory(b) => b.len() as u64,
            ByteSource::FileRange { len, .. } => *len,
            ByteSource::Generated { len, .. } => *len,
        }
    }

    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }

    /// Realize the bytes. For `FileRange`, reads exactly the window via seek —
    /// allocating only `len` bytes regardless of the file's total size. Callers
    /// that hand the source to a streaming writer should prefer `read_chunk` so
    /// no single allocation exceeds one chunk.
    pub fn read(&self) -> Result<Vec<u8>, MediaError> {
        match self {
            ByteSource::Memory(b) => Ok(b.clone()),
            ByteSource::FileRange { path, offset, len } => {
                let mut f = File::open(path)?;
                f.seek(SeekFrom::Start(*offset))?;
                let mut buf = vec![0u8; *len as usize];
                let n = read_full(&mut f, &mut buf)?;
                buf.truncate(n);
                Ok(buf)
            }
            ByteSource::Generated { len, seed } => Ok((0..*len)
                .map(|i| (i.wrapping_mul(2654435761).wrapping_add(*seed)) as u8)
                .collect()),
        }
    }

    /// Read at most `max` bytes starting `chunk_offset` into the source. Returns
    /// `Ok(Vec::new())` when `chunk_offset >= self.len()`. The allocation is
    /// bounded by `max`, never by the source's total length — so a multi-GB
    /// `FileRange` streams without ever materializing the whole window.
    pub fn read_chunk(&self, chunk_offset: u64, max: usize) -> Result<Vec<u8>, MediaError> {
        let total = self.len();
        if chunk_offset >= total || max == 0 {
            return Ok(Vec::new());
        }
        let want = ((total - chunk_offset).min(max as u64)) as usize;
        match self {
            ByteSource::Memory(b) => {
                let start = chunk_offset as usize;
                Ok(b[start..start + want].to_vec())
            }
            ByteSource::FileRange { path, offset, .. } => {
                let mut f = File::open(path)?;
                f.seek(SeekFrom::Start(*offset + chunk_offset))?;
                let mut buf = vec![0u8; want];
                let n = read_full(&mut f, &mut buf)?;
                buf.truncate(n);
                Ok(buf)
            }
            ByteSource::Generated { seed, .. } => Ok((chunk_offset..chunk_offset + want as u64)
                .map(|i| (i.wrapping_mul(2654435761).wrapping_add(*seed)) as u8)
                .collect()),
        }
    }
}

fn read_full(f: &mut File, buf: &mut [u8]) -> std::io::Result<usize> {
    let mut filled = 0;
    while filled < buf.len() {
        match f.read(&mut buf[filled..])? {
            0 => break,
            n => filled += n,
        }
    }
    Ok(filled)
}

#[derive(Debug, Clone)]
struct Entry {
    handle: ObjectHandle,
    path: PathBuf,
    parent: ObjectHandle,
    is_dir: bool,
    size: u64,
    format: u16,
}

#[derive(Debug, Default, Clone, Copy)]
pub struct ObjectQuery {
    /// `Some(0)` means top-level (root) objects; `Some(h)` children of `h`.
    pub parent: Option<ObjectHandle>,
    pub format: Option<u16>,
}

#[derive(Debug, Default)]
pub struct ScanSummary {
    pub objects: usize,
    pub bytes: u64,
}

pub struct MediaStore {
    root: PathBuf,
    by_handle: BTreeMap<ObjectHandle, Entry>,
}

impl MediaStore {
    /// Open a store rooted at `root`. The root is canonicalized; all later
    /// traversal is confined beneath it.
    pub fn open(root: impl AsRef<Path>) -> Result<Self, MediaError> {
        let root = root.as_ref().canonicalize()?;
        Ok(MediaStore {
            root,
            by_handle: BTreeMap::new(),
        })
    }

    pub fn root(&self) -> &Path {
        &self.root
    }

    /// Walk the card and assign stable handles. Handles are assigned in sorted
    /// path order so the same card yields the same handles across runs.
    /// Symlinks whose target escapes the root are skipped.
    pub fn scan(&mut self) -> Result<ScanSummary, MediaError> {
        let mut paths: Vec<(PathBuf, bool, u64)> = Vec::new();
        self.collect(&self.root.clone(), &mut paths)?;
        // Deterministic order -> stable handles.
        paths.sort_by(|a, b| a.0.cmp(&b.0));

        self.by_handle.clear();
        // First pass: assign handles to every path.
        let mut handle_of: BTreeMap<PathBuf, ObjectHandle> = BTreeMap::new();
        for (i, (path, _, _)) in paths.iter().enumerate() {
            handle_of.insert(path.clone(), (i as u32) + 1);
        }
        let mut summary = ScanSummary::default();
        for (path, is_dir, size) in paths {
            let handle = handle_of[&path];
            let parent = path
                .parent()
                .and_then(|p| handle_of.get(p))
                .copied()
                .unwrap_or(0); // 0 = root association
            let format = if is_dir {
                format::ASSOCIATION
            } else {
                format_of(&path)
            };
            if !is_dir {
                summary.bytes += size;
            }
            summary.objects += 1;
            self.by_handle.insert(
                handle,
                Entry {
                    handle,
                    path,
                    parent,
                    is_dir,
                    size,
                    format,
                },
            );
        }
        Ok(summary)
    }

    fn collect(&self, dir: &Path, out: &mut Vec<(PathBuf, bool, u64)>) -> Result<(), MediaError> {
        for entry in std::fs::read_dir(dir)? {
            let entry = entry?;
            let path = entry.path();
            // Resolve symlinks safely: a link whose real target leaves the root
            // is dropped entirely.
            let meta = std::fs::symlink_metadata(&path)?;
            let real = if meta.file_type().is_symlink() {
                match path.canonicalize() {
                    Ok(t) if t.starts_with(&self.root) => t,
                    _ => continue, // escapes root (or dangling) -> skip
                }
            } else {
                path.clone()
            };
            let real_meta = std::fs::metadata(&real)?;
            if real_meta.is_dir() {
                out.push((path.clone(), true, 0));
                self.collect(&path, out)?;
            } else {
                out.push((path.clone(), false, real_meta.len()));
            }
        }
        Ok(())
    }

    fn entry(&self, handle: ObjectHandle) -> Result<&Entry, MediaError> {
        self.by_handle
            .get(&handle)
            .ok_or(MediaError::UnknownHandle(handle))
    }

    /// Confirm a path is inside the root (defense in depth for any external
    /// path).
    pub fn assert_within_root(&self, path: &Path) -> Result<(), MediaError> {
        let canon = path
            .canonicalize()
            .map_err(|_| MediaError::RootEscape(path.to_path_buf()))?;
        if canon.starts_with(&self.root) {
            Ok(())
        } else {
            Err(MediaError::RootEscape(path.to_path_buf()))
        }
    }

    pub fn handles(&self, query: ObjectQuery) -> Vec<ObjectHandle> {
        self.by_handle
            .values()
            .filter(|e| query.parent.map(|p| e.parent == p).unwrap_or(true))
            .filter(|e| query.format.map(|f| e.format == f).unwrap_or(true))
            .map(|e| e.handle)
            .collect()
    }

    /// Generate `ObjectInfo`, applying the 32-bit size ceiling for oversize
    /// objects.
    pub fn object_info(&self, handle: ObjectHandle) -> Result<ObjectInfo, MediaError> {
        let e = self.entry(handle)?;
        let reported_size = e.size.min(SIZE_CEILING) as u32;
        let filename = e
            .path
            .file_name()
            .and_then(|s| s.to_str())
            .unwrap_or("")
            .to_string();
        Ok(ObjectInfo {
            storage_id: 0x0001_0001,
            object_format: e.format,
            object_compressed_size: reported_size,
            parent_object: e.parent,
            association_type: if e.is_dir { 1 } else { 0 },
            filename,
            ..Default::default()
        })
    }

    /// True if the object cannot be wirelessly transferred because its real size
    /// exceeds the 32-bit `ObjectInfo` field (reported at the ceiling).
    pub fn is_memory_card_only(&self, handle: ObjectHandle) -> Result<bool, MediaError> {
        Ok(self.entry(handle)?.size >= SIZE_CEILING)
    }

    pub fn object_size(&self, handle: ObjectHandle) -> Result<u64, MediaError> {
        Ok(self.entry(handle)?.size)
    }

    /// A bounded partial read. Clamps to the object's real length; returns a
    /// `FileRange` so the bytes are streamed, not buffered.
    pub fn read_range(
        &self,
        handle: ObjectHandle,
        offset: u64,
        len: u32,
    ) -> Result<ByteSource, MediaError> {
        let e = self.entry(handle)?;
        let avail = e.size.saturating_sub(offset);
        let len = (len as u64).min(avail);
        Ok(ByteSource::FileRange {
            path: e.path.clone(),
            offset,
            len,
        })
    }

    /// Extract a thumbnail. For RAF, returns the EXIF thumbnail embedded in
    /// the RAF header preview JPEG. For JPEG, returns the file.
    pub fn thumbnail(&self, handle: ObjectHandle) -> Result<ByteSource, MediaError> {
        let e = self.entry(handle)?;
        match e.format {
            fmt::RAF => extract_raf_thumbnail(&e.path),
            format::EXIF_JPEG => Ok(ByteSource::FileRange {
                path: e.path.clone(),
                offset: 0,
                len: e.size,
            }),
            // MOV/HEIF/etc: a generated poster placeholder until a real decoder lands.
            _ => Ok(ByteSource::Generated { len: 0, seed: 0 }),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct FileSpan {
    offset: u64,
    len: u64,
}

fn format_of(path: &Path) -> u16 {
    match path
        .extension()
        .and_then(|s| s.to_str())
        .map(|s| s.to_ascii_lowercase())
        .as_deref()
    {
        Some("jpg") | Some("jpeg") => format::EXIF_JPEG,
        Some("raf") => fmt::RAF,
        Some("mov") => fmt::MOV,
        Some("heif") | Some("heic") => fmt::HEIF,
        _ => format::UNDEFINED,
    }
}

const RAF_HEADER_LEN: usize = 0x5c;
const RAF_PREVIEW_OFFSET_AT: usize = 0x54;
const RAF_PREVIEW_LENGTH_AT: usize = 0x58;

fn extract_raf_thumbnail(path: &Path) -> Result<ByteSource, MediaError> {
    let preview = raf_header_preview(path)?.ok_or(MediaError::NoPreview)?;
    let thumbnail = jpeg_exif_thumbnail(path, preview)?.ok_or(MediaError::NoPreview)?;
    Ok(ByteSource::FileRange {
        path: path.to_path_buf(),
        offset: thumbnail.offset,
        len: thumbnail.len,
    })
}

fn raf_header_preview(path: &Path) -> Result<Option<FileSpan>, MediaError> {
    let mut f = File::open(path)?;
    let file_len = f.metadata()?.len();
    if file_len < RAF_HEADER_LEN as u64 {
        return Ok(None);
    }
    let header = read_at(&mut f, 0, RAF_HEADER_LEN)?;
    if !header.starts_with(b"FUJIFILM") {
        return Ok(None);
    }

    let offset = be_u32(&header[RAF_PREVIEW_OFFSET_AT..RAF_PREVIEW_OFFSET_AT + 4]) as u64;
    let len = be_u32(&header[RAF_PREVIEW_LENGTH_AT..RAF_PREVIEW_LENGTH_AT + 4]) as u64;
    if offset == 0 || len == 0 {
        return Ok(None);
    }
    let end = offset.checked_add(len).ok_or(MediaError::NoPreview)?;
    if end > file_len {
        return Ok(None);
    }
    Ok(Some(FileSpan { offset, len }))
}

fn jpeg_exif_thumbnail(path: &Path, jpeg: FileSpan) -> Result<Option<FileSpan>, MediaError> {
    let mut f = File::open(path)?;
    if read_at(&mut f, jpeg.offset, 2)? != [0xff, 0xd8] {
        return Ok(None);
    }

    let jpeg_end = jpeg
        .offset
        .checked_add(jpeg.len)
        .ok_or(MediaError::NoPreview)?;
    let mut pos = jpeg.offset + 2;
    while pos + 4 <= jpeg_end {
        let marker = read_at(&mut f, pos, 2)?;
        if marker[0] != 0xff {
            return Ok(None);
        }
        pos += 2;

        let mut marker_id = marker[1];
        while marker_id == 0xff && pos < jpeg_end {
            marker_id = read_at(&mut f, pos, 1)?[0];
            pos += 1;
        }

        if marker_id == 0xd9 || marker_id == 0xda {
            return Ok(None);
        }
        if marker_id == 0x01 || (0xd0..=0xd7).contains(&marker_id) {
            continue;
        }
        if pos + 2 > jpeg_end {
            return Ok(None);
        }

        let len = u16::from_be_bytes(read_at(&mut f, pos, 2)?.try_into().unwrap()) as u64;
        if len < 2 {
            return Ok(None);
        }
        let data_offset = pos + 2;
        let data_len = len - 2;
        let next = data_offset
            .checked_add(data_len)
            .ok_or(MediaError::NoPreview)?;
        if next > jpeg_end {
            return Ok(None);
        }

        if marker_id == 0xe1 {
            let data = read_at(&mut f, data_offset, data_len as usize)?;
            if let Some(span) = exif_thumbnail_span(&data) {
                let offset = data_offset
                    .checked_add(span.offset)
                    .ok_or(MediaError::NoPreview)?;
                let end = offset.checked_add(span.len).ok_or(MediaError::NoPreview)?;
                if end <= jpeg_end {
                    return Ok(Some(FileSpan {
                        offset,
                        len: span.len,
                    }));
                }
            }
        }

        pos = next;
    }
    Ok(None)
}

fn read_at(f: &mut File, offset: u64, len: usize) -> Result<Vec<u8>, MediaError> {
    f.seek(SeekFrom::Start(offset))?;
    let mut buf = vec![0u8; len];
    let n = read_full(f, &mut buf)?;
    if n != len {
        return Err(MediaError::NoPreview);
    }
    Ok(buf)
}

fn exif_thumbnail_span(app1_data: &[u8]) -> Option<FileSpan> {
    let tiff = app1_data.strip_prefix(b"Exif\0\0")?;
    let endian = TiffEndian::from_header(tiff)?;
    if tiff_u16(tiff, 2, endian)? != 42 {
        return None;
    }

    let ifd0 = tiff_u32(tiff, 4, endian)? as usize;
    let ifd1 = ifd_next(tiff, ifd0, endian)?;
    let (thumb_offset, thumb_len) = ifd_jpeg_thumbnail(tiff, ifd1, endian)?;
    if thumb_len == 0 {
        return None;
    }
    let thumb_end = thumb_offset.checked_add(thumb_len)?;
    let thumb = tiff.get(thumb_offset..thumb_end)?;
    if !thumb.starts_with(&[0xff, 0xd8]) {
        return None;
    }

    Some(FileSpan {
        offset: (6 + thumb_offset) as u64,
        len: thumb_len as u64,
    })
}

#[derive(Clone, Copy)]
enum TiffEndian {
    Little,
    Big,
}

impl TiffEndian {
    fn from_header(tiff: &[u8]) -> Option<Self> {
        match tiff.get(0..2)? {
            b"II" => Some(Self::Little),
            b"MM" => Some(Self::Big),
            _ => None,
        }
    }
}

fn ifd_next(tiff: &[u8], ifd_offset: usize, endian: TiffEndian) -> Option<usize> {
    let count = tiff_u16(tiff, ifd_offset, endian)? as usize;
    let entries_end = ifd_offset
        .checked_add(2)?
        .checked_add(count.checked_mul(12)?)?;
    let next = tiff_u32(tiff, entries_end, endian)? as usize;
    (next != 0).then_some(next)
}

fn ifd_jpeg_thumbnail(
    tiff: &[u8],
    ifd_offset: usize,
    endian: TiffEndian,
) -> Option<(usize, usize)> {
    let count = tiff_u16(tiff, ifd_offset, endian)? as usize;
    let mut thumb_offset = None;
    let mut thumb_len = None;
    for i in 0..count {
        let entry = ifd_offset.checked_add(2)?.checked_add(i.checked_mul(12)?)?;
        let tag = tiff_u16(tiff, entry, endian)?;
        match tag {
            0x0201 => thumb_offset = Some(ifd_entry_u32(tiff, entry, endian)? as usize),
            0x0202 => thumb_len = Some(ifd_entry_u32(tiff, entry, endian)? as usize),
            _ => {}
        }
    }
    Some((thumb_offset?, thumb_len?))
}

fn ifd_entry_u32(tiff: &[u8], entry: usize, endian: TiffEndian) -> Option<u32> {
    let field_type = tiff_u16(tiff, entry + 2, endian)?;
    let count = tiff_u32(tiff, entry + 4, endian)?;
    if count != 1 {
        return None;
    }
    match field_type {
        3 => tiff_u16(tiff, entry + 8, endian).map(u32::from),
        4 => tiff_u32(tiff, entry + 8, endian),
        _ => None,
    }
}

fn tiff_u16(tiff: &[u8], offset: usize, endian: TiffEndian) -> Option<u16> {
    let bytes: [u8; 2] = tiff.get(offset..offset + 2)?.try_into().ok()?;
    Some(match endian {
        TiffEndian::Little => u16::from_le_bytes(bytes),
        TiffEndian::Big => u16::from_be_bytes(bytes),
    })
}

fn tiff_u32(tiff: &[u8], offset: usize, endian: TiffEndian) -> Option<u32> {
    let bytes: [u8; 4] = tiff.get(offset..offset + 4)?.try_into().ok()?;
    Some(match endian {
        TiffEndian::Little => u32::from_le_bytes(bytes),
        TiffEndian::Big => u32::from_be_bytes(bytes),
    })
}

fn be_u32(bytes: &[u8]) -> u32 {
    u32::from_be_bytes(bytes.try_into().unwrap())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;

    fn tmpdir() -> PathBuf {
        let nanos = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let d = std::env::temp_dir().join(format!("ptpsim-media-{nanos}"));
        std::fs::create_dir_all(&d).unwrap();
        d
    }

    fn write(path: &Path, bytes: &[u8]) {
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        File::create(path).unwrap().write_all(bytes).unwrap();
    }

    fn jpeg_with_exif_thumbnail(thumbnail: &[u8], full_preview_marker: &[u8]) -> Vec<u8> {
        let thumbnail_offset = 44u32;
        let mut tiff = Vec::new();
        tiff.extend_from_slice(b"II");
        tiff.extend_from_slice(&42u16.to_le_bytes());
        tiff.extend_from_slice(&8u32.to_le_bytes());
        tiff.extend_from_slice(&0u16.to_le_bytes());
        tiff.extend_from_slice(&14u32.to_le_bytes());
        tiff.extend_from_slice(&2u16.to_le_bytes());
        tiff.extend_from_slice(&0x0201u16.to_le_bytes());
        tiff.extend_from_slice(&4u16.to_le_bytes());
        tiff.extend_from_slice(&1u32.to_le_bytes());
        tiff.extend_from_slice(&thumbnail_offset.to_le_bytes());
        tiff.extend_from_slice(&0x0202u16.to_le_bytes());
        tiff.extend_from_slice(&4u16.to_le_bytes());
        tiff.extend_from_slice(&1u32.to_le_bytes());
        tiff.extend_from_slice(&(thumbnail.len() as u32).to_le_bytes());
        tiff.extend_from_slice(&0u32.to_le_bytes());
        assert_eq!(tiff.len(), thumbnail_offset as usize);
        tiff.extend_from_slice(thumbnail);

        let mut app1_data = b"Exif\0\0".to_vec();
        app1_data.extend_from_slice(&tiff);
        let app1_len = (app1_data.len() + 2) as u16;
        let comment_len = (full_preview_marker.len() + 2) as u16;

        let mut jpeg = vec![0xff, 0xd8, 0xff, 0xe1];
        jpeg.extend_from_slice(&app1_len.to_be_bytes());
        jpeg.extend_from_slice(&app1_data);
        jpeg.extend_from_slice(&[0xff, 0xfe]);
        jpeg.extend_from_slice(&comment_len.to_be_bytes());
        jpeg.extend_from_slice(full_preview_marker);
        jpeg.extend_from_slice(&[0xff, 0xd9]);
        jpeg
    }

    fn raf_with_header_preview(preview: &[u8]) -> Vec<u8> {
        let preview_offset = 0x94usize;
        let mut raf = vec![0u8; preview_offset];
        raf[0..b"FUJIFILMCCD-RAW".len()].copy_from_slice(b"FUJIFILMCCD-RAW");
        raf[0x3c..0x40].copy_from_slice(b"0201");
        raf[0x54..0x58].copy_from_slice(&(preview_offset as u32).to_be_bytes());
        raf[0x58..0x5c].copy_from_slice(&(preview.len() as u32).to_be_bytes());
        raf.extend_from_slice(preview);
        raf.extend_from_slice(b"raw sensor data");
        raf
    }

    #[test]
    fn scan_assigns_stable_handles_and_filters() {
        let root = tmpdir();
        write(
            &root.join("DCIM/100_FUJI/DSCF0001.JPG"),
            b"\xFF\xD8stuff\xFF\xD9",
        );
        write(&root.join("DCIM/100_FUJI/DSCF0002.RAF"), b"raf");
        let mut s1 = MediaStore::open(&root).unwrap();
        s1.scan().unwrap();
        let mut s2 = MediaStore::open(&root).unwrap();
        s2.scan().unwrap();
        // Stable across independent scans.
        assert_eq!(
            s1.handles(ObjectQuery::default()),
            s2.handles(ObjectQuery::default())
        );
        // Filter by format.
        let jpgs = s1.handles(ObjectQuery {
            parent: None,
            format: Some(format::EXIF_JPEG),
        });
        assert_eq!(jpgs.len(), 1);
        std::fs::remove_dir_all(&root).ok();
    }

    #[test]
    fn symlink_escape_is_rejected_in_root_link_works() {
        let root = tmpdir();
        let outside = tmpdir();
        write(&outside.join("secret.JPG"), b"\xFF\xD8x\xFF\xD9");
        write(&root.join("DCIM/100_FUJI/real.JPG"), b"\xFF\xD8y\xFF\xD9");
        // Escaping symlink.
        #[cfg(unix)]
        std::os::unix::fs::symlink(
            outside.join("secret.JPG"),
            root.join("DCIM/100_FUJI/escape.JPG"),
        )
        .unwrap();
        // In-root symlink.
        #[cfg(unix)]
        std::os::unix::fs::symlink(
            root.join("DCIM/100_FUJI/real.JPG"),
            root.join("DCIM/100_FUJI/inlink.JPG"),
        )
        .unwrap();

        let mut store = MediaStore::open(&root).unwrap();
        store.scan().unwrap();
        let names: Vec<String> = store
            .handles(ObjectQuery::default())
            .into_iter()
            .map(|h| store.object_info(h).unwrap().filename)
            .collect();
        assert!(names.iter().any(|n| n == "real.JPG"));
        assert!(
            names.iter().any(|n| n == "inlink.JPG"),
            "in-root symlink should be visible"
        );
        assert!(
            !names.iter().any(|n| n == "escape.JPG"),
            "escaping symlink must be dropped"
        );

        // Direct guard too.
        assert!(store
            .assert_within_root(&outside.join("secret.JPG"))
            .is_err());
        std::fs::remove_dir_all(&root).ok();
        std::fs::remove_dir_all(&outside).ok();
    }

    #[test]
    fn raf_thumbnail_uses_exif_thumbnail_not_header_preview() {
        let root = tmpdir();
        let thumbnail = b"\xff\xd8TINY-THUMB\xff\xd9";
        let full_marker = b"FULL-HEADER-PREVIEW";
        let preview = jpeg_with_exif_thumbnail(thumbnail, full_marker);
        let raf = raf_with_header_preview(&preview);
        write(&root.join("DCIM/100_FUJI/DSCF9.RAF"), &raf);

        let mut store = MediaStore::open(&root).unwrap();
        store.scan().unwrap();
        let h = store.handles(ObjectQuery {
            parent: None,
            format: Some(fmt::RAF),
        })[0];
        let preview_span = raf_header_preview(&root.join("DCIM/100_FUJI/DSCF9.RAF"))
            .unwrap()
            .expect("RAF header preview");
        assert_eq!(preview_span.offset, 0x94);
        assert_eq!(preview_span.len, preview.len() as u64);

        let src = store.thumbnail(h).unwrap();
        if let ByteSource::FileRange { offset, len, .. } = &src {
            assert_ne!(*offset, preview_span.offset);
            assert_eq!(*len, thumbnail.len() as u64);
        } else {
            panic!("expected a bounded FileRange");
        }
        let bytes = src.read().unwrap();
        assert_eq!(bytes, thumbnail);
        std::fs::remove_dir_all(&root).ok();
    }

    #[test]
    fn oversize_mov_is_ceilinged_without_allocation() {
        let root = tmpdir();
        let p = root.join("DCIM/100_FUJI/BIG.MOV");
        std::fs::create_dir_all(p.parent().unwrap()).unwrap();
        // 5 GiB sparse file: set_len does not allocate blocks.
        let f = File::create(&p).unwrap();
        let five_gib = 5u64 * 1024 * 1024 * 1024;
        f.set_len(five_gib).unwrap();
        drop(f);

        let mut store = MediaStore::open(&root).unwrap();
        store.scan().unwrap();
        let h = store.handles(ObjectQuery {
            parent: None,
            format: Some(fmt::MOV),
        })[0];

        // Real size known; ObjectInfo reports the 32-bit ceiling.
        assert_eq!(store.object_size(h).unwrap(), five_gib);
        assert_eq!(
            store.object_info(h).unwrap().object_compressed_size,
            0xffff_ffff
        );
        assert!(store.is_memory_card_only(h).unwrap());

        // A partial read near the end works, allocating only the window.
        let src = store.read_range(h, five_gib - 8, 16).unwrap();
        assert_eq!(src.len(), 8); // clamped to remaining
        assert_eq!(src.read().unwrap().len(), 8);
        std::fs::remove_dir_all(&root).ok();
    }

    #[test]
    fn read_chunk_streams_without_realizing_full_window() {
        let root = tmpdir();
        let p = root.join("DCIM/100_FUJI/BIG.MOV");
        std::fs::create_dir_all(p.parent().unwrap()).unwrap();
        // 5 GiB sparse file. The whole-window allocation would OOM the test;
        // streaming should bound the allocation by chunk size.
        let f = File::create(&p).unwrap();
        let five_gib = 5u64 * 1024 * 1024 * 1024;
        f.set_len(five_gib).unwrap();
        drop(f);

        // FileRange spanning the full file, larger than any sane buffer.
        let src = ByteSource::FileRange {
            path: p.clone(),
            offset: 0,
            len: five_gib,
        };
        // One chunk reads at most `max` bytes regardless of total length.
        let chunk = src.read_chunk(0, 256 * 1024).unwrap();
        assert_eq!(chunk.len(), 256 * 1024);
        // The last chunk is short.
        let tail = src.read_chunk(five_gib - 100, 256 * 1024).unwrap();
        assert_eq!(tail.len(), 100);
        // Past-the-end is empty, not an error.
        assert!(src.read_chunk(five_gib, 256 * 1024).unwrap().is_empty());
        std::fs::remove_dir_all(&root).ok();
    }

    #[test]
    fn read_chunk_memory_and_generated() {
        let mem = ByteSource::Memory(vec![1, 2, 3, 4, 5, 6, 7, 8]);
        assert_eq!(mem.read_chunk(0, 3).unwrap(), vec![1, 2, 3]);
        assert_eq!(mem.read_chunk(5, 100).unwrap(), vec![6, 7, 8]);
        assert!(mem.read_chunk(8, 1).unwrap().is_empty());

        let gen = ByteSource::Generated {
            len: 1_000_000,
            seed: 42,
        };
        let first = gen.read_chunk(0, 16).unwrap();
        let again = gen.read_chunk(0, 16).unwrap();
        assert_eq!(first, again, "seeded generator is deterministic");
        assert_eq!(first.len(), 16);
    }
}
