[package]
name = "protocol-primitives"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
blowfish = { workspace = true }
ptp-core = { workspace = true }
subtle = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
serde = { workspace = true }
serde_yaml = { workspace = true }
